---
- name: update apt cache
  apt: update_cache=yes

- name: install required packages
  apt: name={{ item }} state=present
  with_items:
    - gcc
    - make
    - git
    - libpcre3-dev
    - openssl
    - libssl-dev
    - rsync
